import type { Exercise } from "./types";

/**
 * A small, hand-built library of gentle mobility movements. Every entry is
 * written to be reassuring and low-risk: slow ranges, clear "how it should
 * feel" cues, and an explicit "stop if" line. This is a wellness companion,
 * not medical guidance.
 */
export const EXERCISES: Exercise[] = [
  {
    id: "breathe-settle",
    name: "Settle & Breathe",
    areas: ["full-body"],
    intensity: "gentle",
    durationSec: 45,
    pose: "breathe",
    summary: "A calm reset to begin — slow breathing to loosen the whole body.",
    steps: [
      "Sit or stand tall with your shoulders relaxed down.",
      "Breathe in slowly through your nose for a count of four.",
      "Let the breath out gently through your mouth for a count of six.",
      "Repeat, letting your jaw, shoulders, and hands soften each time.",
    ],
    howItShouldFeel: "Calming and grounding. Your shoulders should feel a little lower with each breath.",
    stopIf: "you feel dizzy or lightheaded — return to normal breathing.",
  },
  {
    id: "neck-tilt",
    name: "Gentle Neck Release",
    areas: ["neck", "shoulders"],
    intensity: "gentle",
    durationSec: 30,
    pose: "neck-tilt",
    summary: "Slow side-to-side tilts to ease tension at the base of the skull.",
    steps: [
      "Sit or stand tall, shoulders relaxed.",
      "Slowly lower your right ear toward your right shoulder.",
      "Rest there and breathe; keep the opposite shoulder soft and low.",
      "Return to center, then repeat to the left.",
    ],
    howItShouldFeel: "A mild, comfortable stretch along the side of your neck.",
    stopIf: "you feel any pinching, sharp pain, tingling, or numbness in the arms.",
  },
  {
    id: "shoulder-roll",
    name: "Shoulder Rolls",
    areas: ["shoulders", "neck", "upper-back"],
    intensity: "gentle",
    durationSec: 30,
    pose: "shoulder-roll",
    summary: "Loosen the shoulders and upper back with slow circles.",
    steps: [
      "Let your arms hang heavy at your sides.",
      "Lift both shoulders up toward your ears.",
      "Roll them back and down in a slow, smooth circle.",
      "Repeat, keeping the movement unhurried.",
    ],
    howItShouldFeel: "Loosening and warm across the tops of the shoulders.",
    stopIf: "you feel grinding pain or catching in the shoulder joint.",
  },
  {
    id: "chest-open",
    name: "Doorway Chest Opener",
    areas: ["shoulders", "upper-back"],
    intensity: "moderate",
    durationSec: 30,
    pose: "chest-open",
    summary: "Open the chest and front of the shoulders to counter desk posture.",
    steps: [
      "Stand tall and gently draw your shoulder blades together.",
      "Raise your forearms to a comfortable height.",
      "Ease your chest slightly forward until you feel a light opening.",
      "Breathe and keep your lower back neutral — no arching.",
    ],
    howItShouldFeel: "A gentle stretch across the chest and front of the shoulders.",
    stopIf: "you feel strain in the shoulder joint or any pain down the arm.",
  },
  {
    id: "cat-cow",
    name: "Cat–Cow (Seated or on Hands & Knees)",
    areas: ["upper-back", "lower-back"],
    intensity: "gentle",
    durationSec: 45,
    pose: "cat-cow",
    summary: "Wave the spine slowly to wake up the whole back.",
    steps: [
      "Sit tall with hands on your knees, or come to hands and knees.",
      "As you breathe in, gently lift your chest and look slightly up.",
      "As you breathe out, round your back and drop your chin softly.",
      "Move slowly with your breath, one segment at a time.",
    ],
    howItShouldFeel: "Fluid and soothing along the length of your spine.",
    stopIf: "any movement sharpens back pain — reduce the range or stop.",
  },
  {
    id: "seated-twist",
    name: "Supported Seated Twist",
    areas: ["lower-back", "upper-back"],
    intensity: "moderate",
    durationSec: 30,
    pose: "seated-twist",
    summary: "A slow rotation to ease the mid and lower back.",
    steps: [
      "Sit tall in a sturdy chair, feet flat on the floor.",
      "Place one hand on the opposite knee, the other resting behind you.",
      "Lengthen up through the spine, then turn gently toward the back hand.",
      "Breathe, then slowly unwind and repeat on the other side.",
    ],
    howItShouldFeel: "A mild rotational stretch — never forced.",
    stopIf: "you feel any sharp or radiating pain into the hips or legs.",
  },
  {
    id: "child-pose",
    name: "Child's Pose Rest",
    areas: ["lower-back", "hips"],
    intensity: "gentle",
    durationSec: 45,
    pose: "child",
    summary: "A restful fold that lengthens the lower back.",
    steps: [
      "From hands and knees, bring your hips back toward your heels.",
      "Let your arms rest forward and your forehead lower toward the floor.",
      "Use a cushion under your hips or forehead if that feels better.",
      "Breathe into your lower back and let it soften.",
    ],
    howItShouldFeel: "Restful and lengthening through the lower back and hips.",
    stopIf: "you have knee pain that this position aggravates — use padding or skip.",
  },
  {
    id: "knee-hug",
    name: "Single Knee Hug",
    areas: ["lower-back", "hips"],
    intensity: "gentle",
    durationSec: 30,
    pose: "knee-hug",
    summary: "Draw one knee in to release the lower back and hip.",
    steps: [
      "Lie on your back with both knees bent, feet flat.",
      "Gently draw one knee toward your chest with both hands.",
      "Keep the other foot relaxed on the floor and your head down.",
      "Breathe, release, and switch sides.",
    ],
    howItShouldFeel: "A comfortable release in the lower back and back of the hip.",
    stopIf: "you feel any sharp pain in the hip joint or lower back.",
  },
  {
    id: "figure-four",
    name: "Reclined Figure-Four",
    areas: ["hips"],
    intensity: "moderate",
    durationSec: 40,
    pose: "figure-four",
    summary: "Open the outer hip and glute with a supported cross.",
    steps: [
      "Lie on your back with knees bent.",
      "Cross one ankle over the opposite thigh, just above the knee.",
      "Gently draw the supporting thigh toward you until you feel an opening.",
      "Keep your head and shoulders relaxed on the floor; switch sides.",
    ],
    howItShouldFeel: "A moderate stretch deep in the outer hip and glute.",
    stopIf: "you feel pinching at the front of the hip or any knee pain.",
  },
  {
    id: "hamstring",
    name: "Supported Hamstring Stretch",
    areas: ["hips", "knees", "lower-back"],
    intensity: "moderate",
    durationSec: 40,
    pose: "hamstring",
    summary: "Lengthen the back of the thigh without straining the back.",
    steps: [
      "Lie on your back, or sit tall on the edge of a chair.",
      "Extend one leg with a soft, unlocked knee.",
      "Hinge gently from the hips until you feel a light stretch behind the thigh.",
      "Keep your back long, not rounded; breathe and switch sides.",
    ],
    howItShouldFeel: "A gentle pull along the back of the thigh, never behind the knee.",
    stopIf: "you feel tightness or pain behind the knee, or tingling down the leg.",
  },
  {
    id: "calf",
    name: "Standing Calf Stretch",
    areas: ["knees", "full-body"],
    intensity: "gentle",
    durationSec: 30,
    pose: "calf",
    summary: "Ease the calf and ankle with a supported lean.",
    steps: [
      "Stand facing a wall and place both hands on it for support.",
      "Step one foot back, keeping the heel down and the knee straight but soft.",
      "Lean gently toward the wall until you feel a calf stretch.",
      "Breathe, then switch sides.",
    ],
    howItShouldFeel: "A mild stretch through the calf of the back leg.",
    stopIf: "you feel any sharp pain in the achilles, ankle, or knee.",
  },
  {
    id: "quad",
    name: "Supported Standing Quad",
    areas: ["knees", "hips"],
    intensity: "moderate",
    durationSec: 30,
    pose: "quad",
    summary: "Stretch the front of the thigh with balance support.",
    steps: [
      "Stand near a wall or chair and hold on with one hand.",
      "Bend one knee and bring that heel toward your seat.",
      "Hold your ankle if you can reach comfortably; keep knees close together.",
      "Stand tall, breathe, and switch sides.",
    ],
    howItShouldFeel: "A gentle stretch along the front of the thigh.",
    stopIf: "you feel knee pain or pressure at the kneecap — ease off.",
  },
  {
    id: "side-bend",
    name: "Reaching Side Bend",
    areas: ["upper-back", "full-body"],
    intensity: "gentle",
    durationSec: 30,
    pose: "side-bend",
    summary: "Lengthen the side body from hip to fingertips.",
    steps: [
      "Sit or stand tall, feet grounded.",
      "Reach one arm up and lengthen toward the ceiling.",
      "Lean gently to the opposite side, keeping both hips settled.",
      "Breathe into your ribs, return, and switch sides.",
    ],
    howItShouldFeel: "A long, gentle stretch down the side of your torso.",
    stopIf: "you feel any strain in the lower back — reduce the lean.",
  },
];

export const byId = (id: string): Exercise | undefined =>
  EXERCISES.find((e) => e.id === id);
